### ISSUE TITLE
Make this repository private

### ISSUE THREAD

**Issue by kazimuth** [juckele/ppbdp-battlecode#1]
See https://education.github.com/ for discounts on private repositories.

(Or don't, if you want a public repository.)

**Comment by juckele** [comment]
Thanks for the reminder. I had only planned on making this repo private if we started pushing anything that we thought was novel. :)

**Comment by bishoy301** [comment]
Hey, I'm sorry that I wasn't there this morning. My work called me in early to fix some problems and I haven't gotten off until now. Let me know if you'd like to reschedule and when works for you.
